project:
  name: quickstart-ibm-security-guardium-insights
  owner: quickstart-eng@amazon.com
  shorten_stack_name: true
  s3_regional_buckets: true
  package_lambda: false
  regions:
  - us-east-1
  - us-east-2
  - us-west-1
  - us-west-2
  - eu-west-1
  - eu-west-2
  - eu-west-3
  - eu-central-1
  - eu-north-1
  - ap-northeast-1
  - ap-northeast-2
  - ap-northeast-3
  - ap-southeast-1
  - ap-southeast-2
  - ap-south-1
  - sa-east-1
  - ca-central-1
  s3_bucket: ''
tests:
  1AZ-GuardiumInsights:
    parameters:
      # Override these values in .taskcat_overrides.yml
      BootNodeAccessCIDR: override
      KeyPairName: override
      RedhatPullSecret: override
      DomainName: override
      GIProductionSize: override
      NumberOfGINodes: override
      NumberOfDb2DataNodes: override
      GINodeInstanceType: override
      Db2DataNodeInstanceType: override
      NumberOfOCS: override
      HostName: override
      Namespace: override
      RepositoryPassword: override
      AdminPassword: override
      # Defaults
      AvailabilityZones: $[taskcat_genaz_1]
      NumberOfAZs: '1'
      ClusterName: gi-$[taskcat_random-string]
      GIDeploymentLogsBucketName: $[taskcat_autobucket]
      LicenseAgreement: 'I agree'
      QSS3BucketName: $[taskcat_autobucket]
      QSS3BucketRegion: $[taskcat_current_region]
      QSS3KeyPrefix: "quickstart-ibm-security-guardium-insights/"
    regions:
    - us-east-1
    s3_bucket: ''
    template: templates/ibm-security-root.template.yaml